(require 'quail)
(quail-define-package
 "Haskell" "Haskell" "x⃗" t
 "A transliteration scheme for Haskell."
 nil t t t t nil t nil nil nil t)
(quail-define-rules
 ("..." ?⋯)     ("\\dots" ?⋯)
 ("->" ?→)      ("\\to" ?→)
 ("=>" ?⇒)      ("\\To" ?⇒)
 ("~>" ?↝)
 ("8<" ?✂)      ("\\scicors" ?✂)
 ("==" ?≡)      ("\\equiv" ?≡)
 ("!=" ?≠)      ("\\notequiv" ?≠)
                ("\\not" ?¬)
 ("\\*" ?×)     ("\\times" ?×)
 ("\\l" ?λ)     ("\\lambda" ?λ)
 ("\\i" ?ι)     ("\\iota" ?ι)
 ("\\t" ?τ)     ("\\tau" ?τ)
 ("\\s" ?σ)     ("\\sigma" ?σ)
 ("\\o" ?ο)     ("\\omicron" ?ο)
 ("\\k" ?κ)     ("\\kappa" ?κ)
 ("|->" ?↦)     ("\\mapsto" ?↦)
 ("\\<" ?⟨)     ("\\langle" ?⟨)
 ("\\>" ?⟩)     ("\\rangle" ?⟩)
 ("<=" ?≤)      (">=" ?≥)
 ("\\A" ?∀)     ("\\forall" ?∀)
 ("\\E" ?∃)     ("\\exists" ?∃)
                ("\\in" ?∈)
 ("\\e"  ?ε)    ("\\epsilon" ?ε)
 ("\\m" ?μ)     ("\\mu" ?μ)
 ("\\n" ?ν)     ("\\nu" ?ν)
 ("\\8" ?∞)     ("\\infty" ?∞)
 ("\\p" ?π)     ("\\pi" ?π)
 ("\\P" ?Π)     ("\\Pi" ?Π)	
;; ("\\v" ?↓)     ("\\downarrow" ?↓)
;; ("\\ni" ?∉)    ("\\notin" ?∉)
;; ("\\<" ?⊂)     ("\\subset" ?⊂)
 )
